spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mutation-db;DB_CLOSE_DELAY=-1
  test:
    database:
      replace: none
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
